name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Update .yaml file for argoCD
      CI_COMMIT_AUTHOR: apply commit hash
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: bash build.sh ${{ github.sha }}

      - uses: actions/checkout@v3
        with:
          repository: primaustryn/argocd-k8s-configs
          ref: 'main'
          token:  ${{ secrets.ARGOCD_GITHUB_TOKEN }}
      - name: GIT Commit Build deployments.yaml
          # Only run on main branch push (e.g. pull request merge).
        if: github.event_name == 'push'
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "primaustryn@users.noreply.github.com"
          sed '/240109-app-inference/d' deployments.yaml > deployments.new.yaml
          VERSION=$(git rev-parse --short ${{ github.sha }})
          echo "        image: dalbamm/240109-app-inference:${VERSION}"
          echo "        image: dalbamm/240109-app-inference:${VERSION}" >> deployments.new.yaml
          mv deployments.new.yaml deployments.yaml
          git add deployments.yaml
          git commit -m "${{ env.CI_COMMIT_MESSAGE }} - ${{ github.sha }}"
          git push
        